version: '3.4'

services:
  backendexpressnodejs:
    image: backend-express-nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
